apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fernetKey.secretName }}
  labels:
    {{- include "secrets.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  fernet-key: {{ .Values.fernetKey.secretValue | b64enc | quote }}
type: Opaque