apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ .Values.gitSshKey.secretName }}
  labels:
    {{- include "secrets.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  keys:
    - private_key
  path: "{{ .Values.gitSshKey.vaultMountPath }}/{{ .Values.gitSshKey.vaultSecretName }}"
  templates:
    gitSshKey: "{% .Secrets.private_key %}"
  type: Opaque