apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ .Values.oidc.secretName }}
  labels:
    {{- include "secrets.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  keys:
    - client_id
    - client_secret
  path: "{{ .Values.oidc.vaultMountPath }}/{{ .Values.oidc.vaultSecretName }}"
  templates:
    clientID: "{% .Secrets.client_id %}"
    clientSecret: "{% .Secrets.client_secret %}"
  type: Opaque