apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis-password
  labels:
    {{- include "secrets.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  password: {{ .Values.redis.secretValue | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.brokerUrlSecretName }}
  labels:
    {{- include "secrets.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  connection: {{ urlJoin (dict "scheme" "redis" "userinfo" (printf ":%s" ( .Values.redis.secretValue | urlquery)) "host" (printf "%s-redis:6379" .Values.redis.airflowReleaseName ) "path" "/0") | b64enc | quote }}