apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.webserver.secretName }}
  labels:
    {{- include "secrets.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  webserver-secret-key: {{ .Values.webserver.secretValue | b64enc | quote }}
type: Opaque