apiVersion: v1
kind: Service
metadata:
  name: {{ include "shs.fullname" . }}
  labels:
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    {{- include "shs.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      name: webui
  selector:
    {{- include "shs.selectorLabels" . | nindent 4 }}
