{{- range $secretName, $secretValue := .Values.vaultSecrets }}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "jdbc-connections.labels" $ | nindent 4 }}
  {{- with $.Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  keys:
    - login
    - password
    - host
    - port
    - schema
  path: "{{ $secretValue.vaultMountPath }}/{{ $secretValue.vaultSecretName }}"
  type: Opaque
  templates:
    {{ $secretValue.envNamePrefix }}_USERNAME: "{% .Secrets.login %}"
    {{ $secretValue.envNamePrefix }}_PASSWORD: "{% .Secrets.password %}"
    {{ $secretValue.envNamePrefix }}_HOST: "{% .Secrets.host %}"
    {{ $secretValue.envNamePrefix }}_PORT: "{% .Secrets.port %}"
    {{ $secretValue.envNamePrefix }}_DATABASE: "{% .Secrets.schema %}"
---
{{- end }}