{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "spark.fullname" . }}-role-binding
  labels:
    {{- include "spark.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "spark.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "spark.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
