{{ $eksClusterName := .Values.eksClusterName}}
{{- range $k, $v := .Values.nodeClasses }}
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: {{ $k }}
  labels:
    karpenter-component: ec2-node-class
    {{- include "karpenter.labels" $ | nindent 4 }}
spec:
  # Required, resolves a default ami and userdata
  amiFamily: {{ $v.amiFamily | default "AL2" }}
  # Required, discovers subnets to attach to instances
  # Each term in the array of subnetSelectorTerms is ORed together
  # Within a single term, all conditions are ANDed
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ $eksClusterName }}
  # Required, discovers security groups to attach to instances
  # Each term in the array of securityGroupSelectorTerms is ORed together
  # Within a single term, all conditions are ANDed
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ $eksClusterName }}
  # Optional, propagates tags to underlying EC2 resources
  tags:
    karpenter.sh/discovery: {{ $eksClusterName }}
    {{- with $v.tags }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $v.blockDeviceMappings }}
  # Optional, configures storage devices for the instance
  blockDeviceMappings:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $v.userData }}
  # Optional, overrides autogenerated userdata with a merge semantic
  userData: {{- toYaml . | indent 2 }}
  {{- end }}
  # Optional, configures detailed monitoring for the instance
  detailedMonitoring: {{ $v.detailedMonitoring }}
{{- end }}
